### ISSUE TITLE
increase size of table

### ISSUE THREAD

**Issue by ShinyFabio** [egonw/r-gprofiler2#4]
Hi,
is it possible to increase the size of the table that comes from `publish_gosttable()`? I use the following code:

```
    gprofiler2::publish_gosttable(dataforgost, highlight_terms = terms,
                      use_colors = TRUE,
                      show_columns = c("source", "term_name", "term_size", "intersection_size"),
          filename = NULL)
```

Here's the problem inside my shiny app. The plot is interactive.

![gosttable](https://user-images.githubusercontent.com/78078351/207379967-dbb000dd-1410-403f-abf7-6f7d61d46023.png)

**Comment by egonw** [comment]
Hi sorry, I did not see this issue report here. This repo is a copy of https://gl.cs.ut.ee/biit/r-gprofiler2

I am not a developer of r-gprofiler2 myself and cannot help. The developers can be found at https://gl.cs.ut.ee/biit/r-gprofiler2 and I recommend filing the issue there.
